kind: pipeline
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build

  - name: publish
    image: plugins/docker
    when:
      branch: master
      event: push
    settings:
      repo: heywesty/heywesty.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
