kind: pipeline
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm build

- name: publish
  image: plugins/docker
  when:
    event:
      - tag
  settings:
    repo: heywesty/heywesty.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
